### ISSUE TITLE
请问有计划发布一个HuggingFace或者Replicate的在线试用demo么？

### ISSUE THREAD

**Issue by qibinlou** [forchchch/DisenBooth#2]
有可能的话想测试下效果，谢谢！

Leo

**Comment by forchchch** [comment]
抱歉，目前我们没有足够的计算资源发布在线试用demo

**Comment by qibinlou** [comment]
FYI Replicate上的public model不需要自己付费，使用的人按次付费即可~  不过我已经通过Colab测试过你们的model了。感谢！
