### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by xingyue-333** [forchchch/DisenBooth#6]
Thank you so much for offerring this repo. Could you please share the code for calculating the CLIP-T score and the DINO score? When calculating the DINO score, how was the reference image selected? Also, for calculating the CLIP-T score, did you use the text 'A dog</w> dog in a bucket' or 'A dog in a bucket'?

**Comment by forchchch** [comment]
I am sorry that the code is missing due to some infra problems. The DINO score is the average score for all the reference images. For the text, we use "a dog in a bucket".
